@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkxlYW5uZSBHcmFoYW0iLCJ1c2VybmFtZSI6IkJyZXQiLCJpYXQiOjE1OTQ4NTg5Mzh9.Uz8n0LL58qYnb2Qzp0QdFRnNdme0cyDnGicZy_8zegQ
GET http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

#########
GET http://localhost:3000/api/total HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


#########
GET http://localhost:3000/api/recovered HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


#########
GET http://localhost:3000/api/chile HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}



#########
POST  http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json 

{
    "email": "Sincere@april.biz",
    "password": "secret"
}